# Salary prediction pipeline

This notebook checks the shared training flow with a smaller model comparison. The full seeded Optuna,
stacking, MLflow, and export run lives in `src/train.py`.

## Load and build deterministic features

`clean()` standardizes text and records missing fields. It does not learn imputation values.

In [1]:
import sys
sys.path.insert(0, "..")

import joblib
import pandas as pd

from src.config import ROOT, load_config
from src.data import clean, load_raw
from src.features import build_features

cfg = load_config()
df = build_features(clean(load_raw(ROOT / cfg["data"]["path"])), cfg["skills"])
X = df.drop(columns=[cfg["data"]["target"]])
y = df[cfg["data"]["target"]]
print("features:", list(X.columns))

features: ['Job_Title', 'Experience_Years', 'Education_Level', 'Location', 'Job_Title_missing', 'Experience_Years_missing', 'Education_Level_missing', 'Location_missing', 'Skills_missing', 'Python', 'Java', 'C++', 'JavaScript', 'Go', 'SQL', 'Spark', 'AWS', 'Docker', 'Kubernetes', 'PyTorch', 'TensorFlow', 'React', 'System Design', 'Agile', 'skill_count']

## Split before learned preprocessing

The test split is set aside here. Median and most-frequent imputers are fitted inside each model
pipeline, so cross-validation folds do not share learned preprocessing statistics.

In [2]:
from sklearn.model_selection import train_test_split
from src.data import cap_outliers_iqr

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=cfg["split"]["test_size"], random_state=cfg["split"]["random_state"]
)
y_train = cap_outliers_iqr(y_train, cfg["outlier_iqr_factor"])
X_train.shape, X_test.shape

((86188, 25), (21547, 25))

## Build the pipeline

`build_pipeline` combines train-fitted imputation, numeric scaling, categorical one-hot encoding, and
the regressor. `TransformedTargetRegressor` handles the salary log transform and inverse transform.

In [3]:
from src.pipeline import build_pipeline
from catboost import CatBoostRegressor

num, cat = cfg["numeric_features"], cfg["categorical_features"]
example = build_pipeline(CatBoostRegressor(iterations=300, verbose=False, random_seed=42), num, cat)
example

TransformedTargetRegressor(func=<ufunc 'log1p'>, inverse_func=<ufunc 'expm1'>,
                           regressor=Pipeline(steps=[('preprocessor',
                                                      ColumnTransformer(remainder='passthrough',
                                                                        transformers=[('num',
                                                                                       Pipeline(steps=[('imputer',
                                                                                                        SimpleImputer(strategy='median')),
                                                                                                       ('scaler',
                                                                                                        StandardScaler())]),
                                                                                       ['Experience_Years',
                                                                                        'skill_count']),
                                                                                      ('cat',
                                                                                       Pipeline(steps=[('imputer',
                                                                                                        SimpleImputer(strategy='most_frequent')),
                                                                                                       ('onehot',
                                                                                                        OneHotEncoder(handle_unknown='ignore',
                                                                                                                      sparse_output=False))]),
                                                                                       ['Job_Title',
                                                                                        'Location',
                                                                                        'Education_Level'])])),
                                                     ('model',
                                                      CatBoostRegressor(iterations=300, loss_function='RMSE', random_seed=42, verbose=False))]))

## Compare models with training-only CV

The same seeded 30,000-row training subset and three folds are used for each baseline. This table is
for model comparison; the held-out test result comes only from the already selected exported model.

In [4]:
from catboost import CatBoostRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import cross_val_score
from xgboost import XGBRegressor

models = {
    "ElasticNet": ElasticNet(alpha=0.01, l1_ratio=0.5, random_state=42),
    "Random Forest": RandomForestRegressor(
        n_estimators=200, max_depth=12, random_state=42, n_jobs=-1
    ),
    "XGBoost": XGBRegressor(
        n_estimators=100, max_depth=5, learning_rate=0.1, random_state=42, n_jobs=-1
    ),
    "CatBoost": CatBoostRegressor(
        iterations=300,
        depth=6,
        learning_rate=0.05,
        random_seed=42,
        verbose=False,
        allow_writing_files=False,
    ),
}

selection_X = X_train.sample(n=min(30_000, len(X_train)), random_state=42)
selection_y = y_train.loc[selection_X.index]
rows = []
for name, model in models.items():
    pipe = build_pipeline(model, num, cat)
    scores = cross_val_score(
        pipe,
        selection_X,
        selection_y,
        cv=cfg["tuning"]["cv_folds"],
        scoring="r2",
        n_jobs=1,
    )
    rows.append({"model": name, "mean_cv_r2": scores.mean(), "std_cv_r2": scores.std()})

pd.DataFrame(rows).set_index("model").round(4)

               mean_cv_r2  std_cv_r2
model
ElasticNet         0.7745     0.0022
Random Forest      0.8248     0.0013
XGBoost            0.8771     0.0021
CatBoost           0.8829     0.0021

## Full training and promotion

`python -m src.train` keeps training-only CV, promotion validation, and final-test reporting as separate stages. It logs the selected sklearn pipeline to the local MLflow registry and only updates the local fallback when promotion passes.

## Exported result

The code below reads the current exported metadata whenever it is run. Its saved output is retained from the earlier pre-registry stacking run, so those displayed numbers are historical rather than the current result. The current artifact and README identify tuned CatBoost with 0.8802 selection CV R² and 0.8841 final-test R².

In [5]:
meta = joblib.load(ROOT / cfg["output"]["metadata"])
print("selected model:", meta["model_name"])
print(f"selection CV R2: {meta['selection_cv_r2']:.4f}")
print(f"test MAE : Rs {meta['mae']:,.0f} (~{meta['mae']/1e5:.2f} LPA)")
print(f"test RMSE: Rs {meta['rmse']:,.0f}")
print(f"test R2  : {meta['r2']:.4f}")
print(f"test MAPE: {meta['mape']:.3f}")

pd.DataFrame(meta["cv_results"]).T.rename(
    columns={"mean": "mean_cv_r2", "std": "std_cv_r2"}
).sort_values("mean_cv_r2", ascending=False).round(4)

selected model: stacking
selection CV R2: 0.8838
test MAE : Rs 155,014 (~1.55 LPA)
test RMSE: Rs 207,766
test R2  : 0.8849
test MAPE: 0.103

                mean_cv_r2  std_cv_r2
stacking            0.8838     0.0020
catboost_tuned      0.8838     0.0020
catboost            0.8829     0.0021
xgboost_tuned       0.8808     0.0015
xgboost             0.8771     0.0021
random_forest       0.8248     0.0013
elasticnet          0.7745     0.0022